### ISSUE TITLE
0.9.1 has been released multiple times

### ISSUE THREAD

**Issue by jd** [smontanaro/pylockfile#11]
The version 0.9.1 has been released on PyPI, modified, and then _released_ again.

So there is several version of the 0.9.1 release out there.

We have been bitten by this because we had installed/cached the first release of 0.9.1 which doesn't work with Python 3.3/3.4, whereas the 0.9.1 release on PyPI does work.

So a 0.9.1.1 or 0.9.2 release should done ASAP to fix this issue IMHO.

**Comment by smontanaro** [comment]
> The version 0.9.1 has been released on PyPI, modified, and then released again.

I see that in the log at the bottom of this page.

https://pypi.python.org/pypi?:action=display&name=lockfile&version=0.9.1

The change involved updating the download URL and Trove classifiers.
The entire episode lasted 20 minutes. It's been awhile since I did
that, but I don't think there were any code changes. Can you point to
two instances of the release which contain different code?

S

**Comment by jd** [comment]
The log is likely not visible to non project owner, so I'll have to trust you on this one. :)

The version we have on our CI server at OpenStack has been downloaded on March 2013.

The difference between the old 0.9.1 and the new one is at least the commits from Python 3 support done on 24 Feb

https://github.com/smontanaro/pylockfile/commit/379fa0b6131995f96f5bd048906fc0bd3c2527f7

**Comment by fungi** [comment]
Specifically, this tarball was mirrored from PyPI on March 25, 2013: http://pypi.openstack.org/openstack/lockfile/lockfile-0.9.1.tar.gz

**Comment by smontanaro** [comment]
Would releasing 0.9.2 solve the problem? Do I have to do something to
prevent people from continuing to download 0.9.1 (other than the usual PyPI
hiding)?

**Comment by fungi** [comment]
Well, releasing a new version on PyPI partly solves the issue in that projects depending on the "latest" version of lockfile could expect consistent behavior from all 0.9.2 downloads. It obviously doesn't help any projects pinning <=0.9.1 or ==0.9.1 since their users would still potentially see inconsistencies depending on when they originally downloaded it.

I'm not sure what the best practice is for dealing with this sort of cleanup, but I'll ping one of the PyPI maintainers to weigh in.

**Comment by dstufft** [comment]
There's not really a good way out of this situation. You're going to have some level of breakage and you just need to pick your poison:
1. Pick the first 0.9.1 - Possibly break anyone who depended on something in the other.
2. Pick the second 0.9.1 - Possibly break anyone who depended on something in the other.
3. Remove it all together - Possibly break for anyone who depended on 0.9.1 explicitly in some form.

**Comment by jd** [comment]
Ping. This is a serious blocker for us that wants to support Python 3 correctly right now.

**Comment by smontanaro** [comment]
On Tue, Jun 10, 2014 at 10:06 AM, Julien Danjou notifications@github.com
wrote:

> This is a serious blocker for us that wants to support Python 3 correctly
> right now.

​What do you propose I do?

I appreciate the bind you folks are in. Still, I am not all that
sympathetic. I haven't supported this package in a few years and, though I
have tried a couple times, I have been unable to get anybody to take it
over.  When I have found people who were nominally interested in taking it
over, they wanted me to do a bunch of legwork to hand it over. "Oh no, I
couldn't possibly work with it while it's in (Google Code|Subversion|etc).
You'll have to get it into (GitHub|Bitbucket|git|hg|whatever) before I will
touch it." Part of the current problem was caused by my attempts to appease
people in the past while knowing little about the process of formally
releasing such a package (or trying to use tools I had never before used).

**Comment by jd** [comment]
We use it in OpenStack so we can take it over if needed. Just let me know I'll handle that with @dhellmann and others.

**Comment by jd** [comment]
Patch proposed to the OpenStack infra config repo to import pylockfile https://review.openstack.org/#/c/101911/

**Comment by OOPMan** [comment]
What's the status of this takeover? Can we expect a new package in PyPi anytime soon?>

**Comment by smontanaro** [comment]
I added a couple people as contributors. Haven't heard from them that they
need anything more from me.

S

**Comment by OOPMan** [comment]
Cool, good to know :-)

**Comment by ethanfurman** [comment]
On 08/05/2014 05:40 AM, Adam Jorgensen wrote:

> What's the status of this takeover? Can we expect a new package in PyPi anytime soon?>

Should be a new package by the end of the month.  :)

## 

~Ethan~

**Comment by jd** [comment]
We're working on adopting it on the OpenStack side FWIW https://review.openstack.org/#/c/102202/

**Comment by ethanfurman** [comment]
On 08/06/2014 06:00 AM, Julien Danjou wrote:

> We're working on adopting it on the OpenStack side FWIW https://review.openstack.org/#/c/102202/

If you do adopt it, would there be any point in maintaining a copy outside of OpenStack?

Not trying to shirk my newly volunteered for responsibilities, but there's no point in duplicating effort.

## 

~Ethan~

**Comment by jd** [comment]
If we adopt it's just to put our team onto it and have it under our responsibility. We don't want to duplicate the effort at all, and we would be glad to incorporate you and any other current contributors into the new maintenant team.

**Comment by OOPMan** [comment]
@ethanfurman Well, it would be nice if I could use lockfile without having to pull in all of OpenStack? I assume you guys are planning that already though :-)

**Comment by jd** [comment]
Haha, we're just moving the repository and putting our library maintenance team on it, we're not making it that different!

**Comment by jd** [comment]
@smontanaro Could you add openstackci to PyPI so it can publish tarballs?

**Comment by smontanaro** [comment]
I think I did it right (openstackci has the role "owner"). If that's not
right, let me or Ethan know.

**Comment by dhellmann** [comment]
That should cover it, thanks Skip!

**Comment by jd** [comment]
@smontanaro we're now ready and i'll release a new version soon. Maybe you could indicate the move on this repo so it's not used anymore?

**Comment by smontanaro** [comment]
Move where? Have you discussed this with Ethan? He's now marked as an
owner, do can do everything I can do, and will probably do it better.

Skip

**Comment by ethanfurman** [comment]
Post the new location when you have it, and we'll mark this one as deprecated.  Having multiple repo's is a good formula for mass confusion.

**Comment by jd** [comment]
It's up there https://git.openstack.org/cgit/openstack/pylockfile/

**Comment by smontanaro** [comment]
On Wed, Sep 17, 2014 at 12:21 PM, ethanfurman notifications@github.com
wrote:

> Having multiple repo's is a good formula for mass confusion.

Even with just a single developer, as I have learned first-hand...

Thanks for all the assistance. I'm happy to be done with it. Once you've
pushed out a new release I will zap my repo at home and package it up at
work.

Skip

**Comment by ethanfurman** [comment]
Given that we have multiple versions of 0.9.1 already in the wild, I would suggest releasing a 0.9.2 as soon as possible so there is stable footing again.

**Comment by jd** [comment]
@ethanfurman Yeah I'm about to do it ASAP. :)

**Comment by jd** [comment]
A new version has been released so that should be OK now!

**Comment by smontanaro** [comment]
Note that the PyPI page (and the README file on Github) needs to be updated
to reference the new repo.

S

**Comment by ludovic-gasc** [comment]
Hi everybody,

Sorry to distrub you, but I've lost a lot of time to understand the actual situation of pylockfile.
If I understand correctly the situation, smontanaro has stopped the development, it's now openstack that works on this project.

It's a nightmare to find the right repository for pylockfile. On github, the good one is: https://github.com/openstack/pylockfile

To merge places and keep a link with already forks made with this repository (https://github.com/smontanaro/pylockfile), I propose two actions:
1. Remove https://github.com/openstack/pylockfile repository, smontanaro gives admin rights to smontanaro/pylockfile to an openstack guy (@jd ?) ,the openstack guy move smontanaro/pylockfile to openstack/pylockfile, and _enable_ 301 HTTP redirection proposed by github during the move.
2. Update README and setup.py to give the right addresses.

I can make a PR for 2., but for 1., I can't, or if you give me temporally admin rights.

Everybody is agree with that ?
If yes, I propose to do this ASAP, at least 1.

Regards.

**Comment by ludovic-gasc** [comment]
In 1., I've forgotten a step: it's necessary to merge commits from openstack/pylockfile to montanaro/pylockfile before deletion, to retrieve missing commits.
1. It's also necessary to update documentation, I can handle also this point.

**Comment by fungi** [comment]
Until at least recently GitHub only supported creating redirects on moves (renames) within the same organization. I gather they've added a "transfer" option now to do something similar between organizations, but I haven't yet tested it myself.

If this does end up happening, the commits won't get "merged" but rather the Git source OpenStack uses will be automatically force-pushed in to replace the source in the freshly-transferred repository. Keep in mind that the OpenStack project does not do its development on GitHub--it only mirrors its repositories to GitHub via push replication for the benefit of people who like to use the forking and favorites features here.

**Comment by ludovic-gasc** [comment]
I used it recently between a user and an organisation, it works pretty well. 

No problem for me to force push.

BTW, in openstack workflow, is it possible to make pull requests on github, or it's necessary to use another thing?

**Comment by d0ugal** [comment]
@GMLudo No, pull requests can't be used. We use Gerrit, the workflow is well documented (and really quite simple once you've tried it.)

See: https://wiki.openstack.org/wiki/Gerrit_Workflow

**Comment by ludovic-gasc** [comment]
@d0ugal Ok, no problems with that, I'll do documentation changes via Gerrit.

About repository move, @smontanaro and @jd are you agree with that ?

**Comment by smontanaro** [comment]
Yes.

**Comment by jd** [comment]
Whatever @fungi says, he's my boss on that. :)

**Comment by fungi** [comment]
Reading the instructions at https://help.github.com/articles/transferring-a-repository/ it may not be entirely straightforward. To transfer a repository from a user to an organization, that user needs to be made (at least temporarily) an administrator in the destination organization based on my interpretation of the instructions. I'll have to confer with the rest of the OpenStack project infrastructure team on whether this is a requirement we'll be able to accommodate in some way.

**Comment by smontanaro** [comment]
_sigh_ I thought I was done with this...

**Comment by ludovic-gasc** [comment]
@fungi You're right, but, to my knowledge, you can also create teams in your organization, maybe you could create a team with admin rights, but only on pylockfile repository.
I never tested in this scenario.
If it's impossible, I can also contact Github support, with a link to this discussion.
They could do something for us to handle this special use case.

**Comment by fungi** [comment]
An entirely reasonable alternative is to just merge a change to the defunct repository which replaces all files there with a one-line README saying development has moved to https://git.openstack.org/cgit/openstack/pylockfile and not worry about redirects.

**Comment by dhellmann** [comment]
Good idea, @fungi. See pull request #15.

**Comment by ludovic-gasc** [comment]
It's sad, you'll lose also the page rank on Google. 
I'm not a big fan of this solution.
