### ISSUE TITLE
Git is not up to date compare to pypi

### ISSUE THREAD

**Issue by pypingou** [smontanaro/pylockfile#14]
The version mentionned on github is: 0.9.1: https://github.com/smontanaro/pylockfile/blob/master/setup.py#L3 while pypi has a 0.10.2 versions

Could you please update the github repository to the latest version?

Thanks

**Comment by ethanfurman** [comment]
pylockfile is no longer developed at this location.

It has been moved to:

https://git.openstack.org/cgit/openstack/pylockfile/

**Comment by pypingou** [comment]
Then maybe the README should be updated? https://github.com/smontanaro/pylockfile/blob/master/README

Same thing for the one present in pypi: https://pypi.python.org/pypi/lockfile (I ended up here via pypi)

**Comment by pypingou** [comment]
And I'm seeing commits present in this repo that are not present on the openstack repo...

**Comment by pypingou** [comment]
Oh and while we're at it, the documentation at http://pythonhosted.org//lockfile/lockfile.html also needs an update
