### ISSUE TITLE
Unable to use local pip repository during install

### ISSUE THREAD

**Issue by Rollmops** [smontanaro/pylockfile#16]
When using a local repository for pip by adding the parameter --index-url=<local_rep> to the pip3 install command or to the pip.conf file, pip always tries to fetch the pbr dependency from the default pip repository **https://pypi.python.org/simple/pbr/**.

Replacing the **setup_requires** parameter in the setup.py with **install_requires** resolves this issue.
I am not sure if the **setup_requires** was chosen deliberately preventing pip from installing pbr to the system if not already installed. But if not **install_requires** would be a workaround for the strange behaviour of setuptools.

**Comment by ethanfurman** [comment]
pylockfile is no longer maintained here.  Please file new bugs at https://bugs.launchpad.net/pylockfile .
